apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: pj4ut0lex-nodejs 
  janus-idp.io/tekton: pj4ut0lex-nodejs
  backstage.io/kubernetes-id: pj4ut0lex-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: pj4ut0lex-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml